### ISSUE TITLE
get rid of --net=host requirement

### ISSUE THREAD

**Issue by nitschSB** [misery/DockerAusweisApp2#4]
Hi,
I got rid of the `--net=host` requiremet by using `caddy reverse-proxy` (see https://github.com/nitschSB/DockerAusweisApp2PersoSim/commit/116ea61e4c9f4615f08a5e1d3594cfe498a6d520 for details).

Now my collegues with Docker Desktop on Windows and Mac may use it.

Cheers
Mario

**Comment by misery** [comment]
Thanks, I will wait for next major release of AusweisApp2 to fix this.
What is your usecase with PersoSim? What are you doing with the AA2? :-)

**Comment by nitschSB** [comment]
Hi,
some of our projects use the Ausweis and they have a set of smoketests for the fully deployed system that wants to be automated.
