### ISSUE TITLE
Configuration not persistent across startups

### ISSUE THREAD

**Issue by hemker** [misery/DockerAusweisApp2#5]
Hey,
every time I start the container, I am required to do the initial configuration steps (pairing device, collecting history information...).
Is there a way to make the configuration persistent, e.g. a docker volume?

Best
Dennis

**Comment by misery** [comment]
Thanks for the report. I added a VOLUME for the configuration. See https://github.com/misery/DockerAusweisApp2/commit/28bf7bacbe712490ac21368a50c766ed26eb5814
